### ISSUE TITLE
How to cite paper

### ISSUE THREAD

**Issue by zglin0** [grin-compiler/grin#111]
How to cite the paper 'A modern look at GRIN,an optimizing functional language back end∗', I can't find its source

**Comment by Anabra** [comment]
Unfortunately, it hasn't been published yet. We submitted it to a local (but internationally open) conference for a quick approval. That has been more than a year ago. We got a review half a year ago, submitted the corrected version, but still no response. 

I will ask the organizer, and get back to you.

**Comment by Anabra** [comment]
Until then, just use the link to the repo :slightly_smiling_face:

**Comment by zglin0** [comment]
ok thinks!
