### ISSUE TITLE
Consider Renaming

### ISSUE THREAD

**Issue by c50a326** [grin-compiler/grin#27]
Hi,

There is a slightly older and at least as prevalent project https://grin-tech.org/ https://github.com/mimblewimble/grin

Edit: I'm seeing both projects being undertaken seriously, as well as being received seriously within their respective communities... The more mature and successful both of these projects become, the more annoying it may become to query search engines, to talk about without confusion, etc. etc...

**Comment by csabahruska** [comment]
I think that renaming the **grin-tech** organization to **grin-compiler** should be sufficient.
I'd like to leave the **grin** repository name untouched.

**Comment by csabahruska** [comment]
The organization is now renamed to **grin-compiler**.
So the project github repo URL is: https://github.com/grin-compiler/grin
