### ISSUE TITLE
Stop pipeline on errors and add --continue-on-lint option for the current behavior.

### ISSUE THREAD

**Issue by andorp** [grin-compiler/grin#76]
In the [Issue #75 ](https://github.com/grin-compiler/grin/issues/75) the root cause was a non-compliant GRIN program. Although the evaluator was able to run such a program, but it break some assumptions. Those assumptions must have been caught by the linter. The linter couldn't fire because there was no active type-env for the program, which was caused by the HPT result being empty due to the non-compliant program. We should stop the pipeline by default when the HPT-can not be computed, on linter errors, and this restriction should be elevated when a --non-safe option is given to the compiler.

**Comment by andorp** [comment]
@csabahruska @Anabra Any objections?

**Comment by csabahruska** [comment]
I agree, type env should be a requirement for the most strict level of linting.

**Comment by Anabra** [comment]
Agreed.
